name: Build APK Android Studio
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Lay code ve
        uses: actions/checkout@v4

      - name: Cai dat Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cap quyen va Build APK
        run: |
          # Cap quyen chay cho gradle neu co san
          chmod +x gradlew || true
          
          # Chay lenh build xuyen qua cac thu muc, chap ca kts
          ./gradlew assembleDebug || gradle assembleDebug || (sudo apt-get update && sudo apt-get install -y gradle && gradle assembleDebug)

      - name: Day file APK len cho ban tai
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: "**/build/outputs/apk/debug/*.apk"
